add_newline = false
command_timeout = 1000

format = """
$directory\
$git_branch\
$git_status\
$cmd_duration\
$character
"""

right_format = """
$c\
$golang\
$java\
$lua\
$nodejs\
$python\
$jobs\
"""

[character]
error_symbol = "[❯](bold red)"
success_symbol = "[❯](bold green)"

[cmd_duration]
format = '[󰞌 $duration]($style) '
min_time = 15000

[directory]
format = '[$path](bold blue) '
truncation_length = 2
truncate_to_repo = true

[fill]
symbol = " "

[git_branch]
format = '[$symbol$branch(:$remote_branch)](bold 5) '

[git_status]
format = '([\[$all_status$ahead_behind\]](bold red) )'
ahead = ""
behind = ""
deleted = "-"

[jobs]
format = ' [$symbol](bold cyan)'

[package]
disabled = true


[c]
format = ' [$symbol($version(-$name))]($style)'

[golang]
format = ' [$symbol($version)]($style)'

[java]
format = ' [${symbol}(${version})]($style)'

[lua]
format = ' [$symbol($version)]($style)'

[nodejs]
format = ' [$symbol($version)]($style)'

[python]
format = ' [${symbol}${pyenv_prefix}(${version})]($style)[( \($virtualenv\))](bold cyan)'
