add_newline = false
palette = "catppuccin"

format = """
$directory\
$git_branch\
$git_status\
$cmd_duration\
$character
"""

right_format = """
$c\
$golang\
$java\
$lua\
$nodejs\
$python\
$jobs\
"""

[character]
error_symbol = "[❯](bold red)"
success_symbol = "[❯](bold pink)"

[cmd_duration]
format = '[󰞌 $duration]($style) '
min_time = 15000

[directory]
format = '[$path](bold lavender) '
truncation_length = 2
truncate_to_repo = true

[fill]
symbol = " "

[git_branch]
format = '[$symbol$branch(:$remote_branch)](bold flamingo) '

[git_status]
format = '([\[$all_status$ahead_behind\]](bold maroon) )'
ahead = ""
behind = ""
deleted = "-"

[jobs]
format = ' [$symbol](bold mauve)'

[package]
disabled = true


[c]
format = ' [$symbol($version(-$name))]($style)'

[golang]
format = ' [$symbol($version)]($style)'

[java]
format = ' [${symbol}(${version})]($style)'

[lua]
format = ' [$symbol($version)]($style)'

[nodejs]
format = ' [$symbol($version)]($style)'

[python]
format = ' [${symbol}${pyenv_prefix}(${version})]($style)[( \($virtualenv\))](bold cyan)'


[palettes.catppuccin]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
